### ISSUE TITLE
Can't build on M1 Macbook

### ISSUE THREAD

**Issue by techman55** [jdah/minecraft-again#2]
Whenever I try to run `$ make`  from the terminal, it gives this error:

``` 
jack@Jacks-MacBook-Pro minecraft-again % make
mkdir -p ./bin
export LD_PATH="-framework QuartzCore -framework Cocoa -framework Carbon -framework Metal -framework CoreFoundation -framework IOKit"
cd lib/bx && make osx-arm64
make[1]: *** No rule to make target osx-arm64'.  Stop.
make: *** [libs] Error 2 
```

Git shows [this error](https://img.techmandev.com/CCtWMX0WUt3NTT0FAf5J/download) when I open the repo's overview

```
fatal: no submodule mapping found in .gitmodules for path 'lib/bgfx'

Status: 128
```

Help...

**Comment by fnky** [comment]
All submodules were missing. Change the `.gitsubmodule` with the following:

```ini
[submodule "lib/bgfx"]
	path = lib/bgfx
	url = https://github.com/bkaradzic/bgfx.git
[submodule "lib/bimg"]
	path = lib/bimg
	url = https://github.com/bkaradzic/bimg.git
[submodule "lib/bx"]
	path = lib/bx
	url = https://github.com/bkaradzic/bx.git
[submodule "lib/glfw"]
	path = lib/glfw
	url = https://github.com/glfw/glfw.git
[submodule "lib/glm"]
	path = lib/glm
	url = https://github.com/g-truc/glm.git
[submodule "lib/tomlplusplus"]
	path = lib/tomlplusplus
	url = https://github.com/marzer/tomlplusplus
```

Then initi the modules and update:

```
git submodule init
git submodule update
```

**Comment by techman55** [comment]
Just tried it; the error stopped showing up in git, but it still shows the same error when building. Also, I looked around a little more, and saw that VS Code found a lot of errors in the platform.cpp file...


<img width="955" alt="2022-01-16 at 22 54 35@2x" src="https://user-images.githubusercontent.com/45174245/149710204-87f1681b-bda7-4b94-8193-3b53c5b0e47b.png">


I don't know if that helps but let me know if there's anything else I can do.

**Comment by jdah** [comment]
@fnky Thanks for that, the updates `.gitmodules` file has been included with 8125707bcac6d1eb51ad1a4b76ec2b07b9002631

@Techman55 VSCode is going to show a lot of errors because it doesn't have the project structure - I would recommend using a tool like [bear](https://github.com/rizsotto/Bear) and `clangd` if you want proper include paths in the project.

**Comment by gcdsss** [comment]
I updated git submodule, and run `make`, still get the same error.

```
mkdir -p ./bin
export LD_PATH="-framework QuartzCore -framework Cocoa -framework Carbon -framework Metal -framework CoreFoundation -framework IOKit"
cd lib/bx && make osx-arm64
make[1]: *** No rule to make target `osx-arm64'.  Stop.
make: *** [libs] Error 2
```

**Comment by fnky** [comment]
@GuiHva `bx` and `bimg` does not have those targets specified. You will need to add them yourself:

Add the following to `lib/bx/makefile` and `lib/bimg/makefile`:

```make
.build/projects/gmake-osx-arm64:
	$(GENIE) --gcc=osx-arm64 gmake
osx-arm64-debug: .build/projects/gmake-osx-arm64
	make -C .build/projects/gmake-osx-arm64 config=debug
osx-arm64-release: .build/projects/gmake-osx-arm64
	make -C .build/projects/gmake-osx-arm64 config=release
osx-arm64: osx-arm64-debug osx-arm64-release
```

**Comment by gcdsss** [comment]
ok, i added and it's already compiling, but occurred with another error. :(

```
==== Building bin2c (debug) ====
Creating ../../osx-arm64/obj/Debug/bin2c
Creating ../../osx-arm64/obj/Debug/bin2c/tools/bin2c
bin2c.cpp
Linking bin2c
Undefined symbols for architecture arm64:
  "_NSLog", referenced from:
      bx::debugOutput(char const*) in libbxDebug.a(debug.o)
  "___CFStringMakeConstantString", referenced from:
      bx::debugOutput(char const*) in libbxDebug.a(debug.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [../../osx-arm64/bin/bin2cDebug] Error 1
make[2]: *** [bin2c] Error 2
make[1]: *** [osx-arm64-debug] Error 2
make: *** [libs] Error 2
```

**Comment by fnky** [comment]
Which version of Xcode and clang are you using?

```
clang++ -v
xcodebuild -version
```

**Comment by gcdsss** [comment]
This is my environment.

```
system: macOS Monterey 12.1
clang++: 
  Apple clang version 13.0.0 (clang-1300.0.29.30)
  Target: arm64-apple-darwin21.2.0
xcodebuild:
  Xcode 13.2.1
  Build version 13C100
```

**Comment by fnky** [comment]
Ah yes, this is another issue in `bx`.

- In `lib/bx/scripts/toolchain.lua` find the configuration for `"osx-arm64"` (line 1007).
- Add the following in to `linkoptions` list:
  ```diff
		linkoptions {
			"-arch arm64",
  +		"-framework Foundation"
		}
  ```

Then run `make clean` inside the `lib/bx` directory and run `make` again from the root project directory.

**Comment by gcdsss** [comment]
I added, still get the same error:
![image](https://user-images.githubusercontent.com/37131861/149855969-ae01e4ba-a021-488d-b27c-753e2900b72e.png)

**Comment by fnky** [comment]
Make sure to clean your build files (`rm -rf lib/bx/.build`), or use `make clean` inside the `bx` project folder.

**Comment by gcdsss** [comment]
Thank you! finally :), `make clean` does not clean `bx` build, must run `rm -rf lib/bx/.build` to delete pre-build files, compile passing now.

**Comment by fnky** [comment]
You have to change the directory to `lib/bx` before running `make clean` to clean build files for that particular project.

Glad you got it working :)

**Comment by techman55** [comment]
I just followed everything above, and I get a different error:

```
jack@Jacks-MacBook-Pro bx % make                
../bx/tools/bin/darwin/genie                       vs2017
Building configurations...
Running action 'vs2017'...
Generating ".build/projects/vs2017/bx.sln"
Generating ".build/projects/vs2017/bx.vcxproj"
Generating ".build/projects/vs2017/bx.vcxproj.user"
Generating ".build/projects/vs2017/bx.vcxproj.filters"
Generating ".build/projects/vs2017/bin2c.vcxproj"
Generating ".build/projects/vs2017/bin2c.vcxproj.user"
Generating ".build/projects/vs2017/bin2c.vcxproj.filters"
Generating ".build/projects/vs2017/lemon.vcxproj"
Generating ".build/projects/vs2017/lemon.vcxproj.user"
Generating ".build/projects/vs2017/lemon.vcxproj.filters"
Generating ".build/projects/vs2017/bx.test.vcxproj"
Generating ".build/projects/vs2017/bx.test.vcxproj.user"
Generating ".build/projects/vs2017/bx.test.vcxproj.filters"
Generating ".build/projects/vs2017/bx.bench.vcxproj"
Generating ".build/projects/vs2017/bx.bench.vcxproj.user"
Generating ".build/projects/vs2017/bx.bench.vcxproj.filters"
Done. Generated 16/16 projects.
../bx/tools/bin/darwin/genie                       vs2019
Building configurations...
Running action 'vs2019'...
Generating ".build/projects/vs2019/bx.sln"
Generating ".build/projects/vs2019/bx.vcxproj"
Generating ".build/projects/vs2019/bx.vcxproj.user"
Generating ".build/projects/vs2019/bx.vcxproj.filters"
Generating ".build/projects/vs2019/bin2c.vcxproj"
Generating ".build/projects/vs2019/bin2c.vcxproj.user"
Generating ".build/projects/vs2019/bin2c.vcxproj.filters"
Generating ".build/projects/vs2019/lemon.vcxproj"
Generating ".build/projects/vs2019/lemon.vcxproj.user"
Generating ".build/projects/vs2019/lemon.vcxproj.filters"
Generating ".build/projects/vs2019/bx.test.vcxproj"
Generating ".build/projects/vs2019/bx.test.vcxproj.user"
Generating ".build/projects/vs2019/bx.test.vcxproj.filters"
Generating ".build/projects/vs2019/bx.bench.vcxproj"
Generating ".build/projects/vs2019/bx.bench.vcxproj.user"
Generating ".build/projects/vs2019/bx.bench.vcxproj.filters"
Done. Generated 16/16 projects.
../bx/tools/bin/darwin/genie --gcc=android-arm     gmake
Set ANDROID_NDK_CLANG, ANDROID_NDK_ARM, and ANDROID_NDK_ROOT environment variables.
Building configurations...
Running action 'gmake'...
Generating ".build/projects/gmake-android-arm/Makefile"
Generating ".build/projects/gmake-android-arm/bx.make"
Generating ".build/projects/gmake-android-arm/bin2c.make"
Generating ".build/projects/gmake-android-arm/lemon.make"
Generating ".build/projects/gmake-android-arm/bx.test.make"
Generating ".build/projects/gmake-android-arm/bx.bench.make"
Done. Generated 6/6 projects.
../bx/tools/bin/darwin/genie --gcc=android-arm64   gmake
Set ANDROID_NDK_CLANG, ANDROID_NDK_ARM64, and ANDROID_NDK_ROOT environment variables.
Building configurations...
Running action 'gmake'...
Generating ".build/projects/gmake-android-arm64/Makefile"
Generating ".build/projects/gmake-android-arm64/bx.make"
Generating ".build/projects/gmake-android-arm64/bin2c.make"
Generating ".build/projects/gmake-android-arm64/lemon.make"
Generating ".build/projects/gmake-android-arm64/bx.test.make"
Generating ".build/projects/gmake-android-arm64/bx.bench.make"
Done. Generated 6/6 projects.
../bx/tools/bin/darwin/genie --gcc=android-x86     gmake
Set ANDROID_NDK_CLANG, ANDROID_NDK_X86, and ANDROID_NDK_ROOT environment variables.
Building configurations...
Running action 'gmake'...
Generating ".build/projects/gmake-android-x86/Makefile"
Generating ".build/projects/gmake-android-x86/bx.make"
Generating ".build/projects/gmake-android-x86/bin2c.make"
Generating ".build/projects/gmake-android-x86/lemon.make"
Generating ".build/projects/gmake-android-x86/bx.test.make"
Generating ".build/projects/gmake-android-x86/bx.bench.make"
Done. Generated 6/6 projects.
../bx/tools/bin/darwin/genie --gcc=mingw-gcc       gmake
Set MINGW environment variable.
Building configurations...
Running action 'gmake'...
Generating ".build/projects/gmake-mingw-gcc/Makefile"
Generating ".build/projects/gmake-mingw-gcc/bx.make"
Generating ".build/projects/gmake-mingw-gcc/bin2c.make"
Generating ".build/projects/gmake-mingw-gcc/lemon.make"
Generating ".build/projects/gmake-mingw-gcc/bx.test.make"
Generating ".build/projects/gmake-mingw-gcc/bx.bench.make"
Done. Generated 6/6 projects.
../bx/tools/bin/darwin/genie --gcc=linux-gcc       gmake
Building configurations...
Running action 'gmake'...
Generating ".build/projects/gmake-linux/Makefile"
Generating ".build/projects/gmake-linux/bx.make"
Generating ".build/projects/gmake-linux/bin2c.make"
Generating ".build/projects/gmake-linux/lemon.make"
Generating ".build/projects/gmake-linux/bx.test.make"
Generating ".build/projects/gmake-linux/bx.bench.make"
Done. Generated 6/6 projects.
../bx/tools/bin/darwin/genie --gcc=haiku           gmake
Error: invalid value 'haiku' for option 'gcc'
stack traceback:
        [C]: in function 'error'
        [string "_WORKING_DIR        = os.getcwd()..."]:63: in function '_premake_main'
make: *** [all] Error 1
```

Edit: Just remembered that I wasn't sure about where in the file I should put the change recommended below... Is there a particular location they need to go or can they just be appended to the bottom of the makefile?

> @GuiHva `bx` and `bimg` does not have those targets specified. You will need to add them yourself:
> 
> Add the following to `lib/bx/makefile` and `lib/bimg/makefile`:
> 
> ```makefile
> .build/projects/gmake-osx-arm64:
> 	$(GENIE) --gcc=osx-arm64 gmake
> osx-arm64-debug: .build/projects/gmake-osx-arm64
> 	make -C .build/projects/gmake-osx-arm64 config=debug
> osx-arm64-release: .build/projects/gmake-osx-arm64
> 	make -C .build/projects/gmake-osx-arm64 config=release
> osx-arm64: osx-arm64-debug osx-arm64-release
> ```

**Comment by gcdsss** [comment]
ok, i added in `bx/makefile` `line 123` with these 

![image](https://user-images.githubusercontent.com/37131861/149860941-3dbf90d3-d55e-4725-a476-7101f028c3fa.png)

**Comment by techman55** [comment]
**Yeah, ignore my last comment... I ran make from the lib/bx folder. I really need some sleep :)**

Although I do get this error when running it from the right directory:

```
==== Building bin2c (debug) ====
Linking bin2c
Undefined symbols for architecture arm64:
  "_NSLog", referenced from:
      bx::debugOutput(char const*) in libbxDebug.a(debug.o)
  "___CFStringMakeConstantString", referenced from:
      bx::debugOutput(char const*) in libbxDebug.a(debug.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [../../osx-arm64/bin/bin2cDebug] Error 1
make[2]: *** [bin2c] Error 2
make[1]: *** [osx-arm64-debug] Error 2
make: *** [libs] Error 2
```

> I just followed everything above, and I get a different error:
> 
> ```
> jack@Jacks-MacBook-Pro bx % make                
> ../bx/tools/bin/darwin/genie                       vs2017
> Building configurations...
> Running action 'vs2017'...
> Generating ".build/projects/vs2017/bx.sln"
> Generating ".build/projects/vs2017/bx.vcxproj"
> Generating ".build/projects/vs2017/bx.vcxproj.user"
> Generating ".build/projects/vs2017/bx.vcxproj.filters"
> Generating ".build/projects/vs2017/bin2c.vcxproj"
> Generating ".build/projects/vs2017/bin2c.vcxproj.user"
> Generating ".build/projects/vs2017/bin2c.vcxproj.filters"
> Generating ".build/projects/vs2017/lemon.vcxproj"
> Generating ".build/projects/vs2017/lemon.vcxproj.user"
> Generating ".build/projects/vs2017/lemon.vcxproj.filters"
> Generating ".build/projects/vs2017/bx.test.vcxproj"
> Generating ".build/projects/vs2017/bx.test.vcxproj.user"
> Generating ".build/projects/vs2017/bx.test.vcxproj.filters"
> Generating ".build/projects/vs2017/bx.bench.vcxproj"
> Generating ".build/projects/vs2017/bx.bench.vcxproj.user"
> Generating ".build/projects/vs2017/bx.bench.vcxproj.filters"
> Done. Generated 16/16 projects.
> ../bx/tools/bin/darwin/genie                       vs2019
> Building configurations...
> Running action 'vs2019'...
> Generating ".build/projects/vs2019/bx.sln"
> Generating ".build/projects/vs2019/bx.vcxproj"
> Generating ".build/projects/vs2019/bx.vcxproj.user"
> Generating ".build/projects/vs2019/bx.vcxproj.filters"
> Generating ".build/projects/vs2019/bin2c.vcxproj"
> Generating ".build/projects/vs2019/bin2c.vcxproj.user"
> Generating ".build/projects/vs2019/bin2c.vcxproj.filters"
> Generating ".build/projects/vs2019/lemon.vcxproj"
> Generating ".build/projects/vs2019/lemon.vcxproj.user"
> Generating ".build/projects/vs2019/lemon.vcxproj.filters"
> Generating ".build/projects/vs2019/bx.test.vcxproj"
> Generating ".build/projects/vs2019/bx.test.vcxproj.user"
> Generating ".build/projects/vs2019/bx.test.vcxproj.filters"
> Generating ".build/projects/vs2019/bx.bench.vcxproj"
> Generating ".build/projects/vs2019/bx.bench.vcxproj.user"
> Generating ".build/projects/vs2019/bx.bench.vcxproj.filters"
> Done. Generated 16/16 projects.
> ../bx/tools/bin/darwin/genie --gcc=android-arm     gmake
> Set ANDROID_NDK_CLANG, ANDROID_NDK_ARM, and ANDROID_NDK_ROOT environment variables.
> Building configurations...
> Running action 'gmake'...
> Generating ".build/projects/gmake-android-arm/Makefile"
> Generating ".build/projects/gmake-android-arm/bx.make"
> Generating ".build/projects/gmake-android-arm/bin2c.make"
> Generating ".build/projects/gmake-android-arm/lemon.make"
> Generating ".build/projects/gmake-android-arm/bx.test.make"
> Generating ".build/projects/gmake-android-arm/bx.bench.make"
> Done. Generated 6/6 projects.
> ../bx/tools/bin/darwin/genie --gcc=android-arm64   gmake
> Set ANDROID_NDK_CLANG, ANDROID_NDK_ARM64, and ANDROID_NDK_ROOT environment variables.
> Building configurations...
> Running action 'gmake'...
> Generating ".build/projects/gmake-android-arm64/Makefile"
> Generating ".build/projects/gmake-android-arm64/bx.make"
> Generating ".build/projects/gmake-android-arm64/bin2c.make"
> Generating ".build/projects/gmake-android-arm64/lemon.make"
> Generating ".build/projects/gmake-android-arm64/bx.test.make"
> Generating ".build/projects/gmake-android-arm64/bx.bench.make"
> Done. Generated 6/6 projects.
> ../bx/tools/bin/darwin/genie --gcc=android-x86     gmake
> Set ANDROID_NDK_CLANG, ANDROID_NDK_X86, and ANDROID_NDK_ROOT environment variables.
> Building configurations...
> Running action 'gmake'...
> Generating ".build/projects/gmake-android-x86/Makefile"
> Generating ".build/projects/gmake-android-x86/bx.make"
> Generating ".build/projects/gmake-android-x86/bin2c.make"
> Generating ".build/projects/gmake-android-x86/lemon.make"
> Generating ".build/projects/gmake-android-x86/bx.test.make"
> Generating ".build/projects/gmake-android-x86/bx.bench.make"
> Done. Generated 6/6 projects.
> ../bx/tools/bin/darwin/genie --gcc=mingw-gcc       gmake
> Set MINGW environment variable.
> Building configurations...
> Running action 'gmake'...
> Generating ".build/projects/gmake-mingw-gcc/Makefile"
> Generating ".build/projects/gmake-mingw-gcc/bx.make"
> Generating ".build/projects/gmake-mingw-gcc/bin2c.make"
> Generating ".build/projects/gmake-mingw-gcc/lemon.make"
> Generating ".build/projects/gmake-mingw-gcc/bx.test.make"
> Generating ".build/projects/gmake-mingw-gcc/bx.bench.make"
> Done. Generated 6/6 projects.
> ../bx/tools/bin/darwin/genie --gcc=linux-gcc       gmake
> Building configurations...
> Running action 'gmake'...
> Generating ".build/projects/gmake-linux/Makefile"
> Generating ".build/projects/gmake-linux/bx.make"
> Generating ".build/projects/gmake-linux/bin2c.make"
> Generating ".build/projects/gmake-linux/lemon.make"
> Generating ".build/projects/gmake-linux/bx.test.make"
> Generating ".build/projects/gmake-linux/bx.bench.make"
> Done. Generated 6/6 projects.
> ../bx/tools/bin/darwin/genie --gcc=haiku           gmake
> Error: invalid value 'haiku' for option 'gcc'
> stack traceback:
>         [C]: in function 'error'
>         [string "_WORKING_DIR        = os.getcwd()..."]:63: in function '_premake_main'
> make: *** [all] Error 1
> ```
> 
> Edit: Just remembered that I wasn't sure about where in the file I should put the change recommended below... Is there a particular location they need to go or can they just be appended to the bottom of the makefile?
> 
> > @GuiHva `bx` and `bimg` does not have those targets specified. You will need to add them yourself:
> > Add the following to `lib/bx/makefile` and `lib/bimg/makefile`:
> > ```makefile
> > .build/projects/gmake-osx-arm64:
> > 	$(GENIE) --gcc=osx-arm64 gmake
> > osx-arm64-debug: .build/projects/gmake-osx-arm64
> > 	make -C .build/projects/gmake-osx-arm64 config=debug
> > osx-arm64-release: .build/projects/gmake-osx-arm64
> > 	make -C .build/projects/gmake-osx-arm64 config=release
> > osx-arm64: osx-arm64-debug osx-arm64-release
> > ```

**Comment by gcdsss** [comment]
yeah, i have occuerred with this error, you just follow my step, it will work

**Comment by fnky** [comment]
@Techman55 https://github.com/jdah/minecraft-again/issues/2#issuecomment-1014996349

**Comment by techman55** [comment]
Oh... I did that at first, and then I discarded all my changes to try and redo everything (in case I typed in something wrong)... must have forgotten that....

Just did those two steps and now it's building for longer than it ever has, so I'll share the final result. Thanks for the help!

**Comment by techman55** [comment]
After a lot of waiting and figuring out that I didn't have cmake installed and remembering the syntax of Homebrew to install it.......... the executable failed to launch with this error 

:( 

![2022-01-17 at 21 17 54@2x](https://user-images.githubusercontent.com/45174245/149865091-227fdbf6-a483-4d66-ba2b-dd6eb4178741.png)

**Comment by gcdsss** [comment]
You still didn't run smoothly? Compiled successfully after i install cmake with `brew install cmake`. run `./bin/game`
![image](https://user-images.githubusercontent.com/37131861/149880253-5dc29e61-8dd4-4315-be07-425b691e6850.png)

**Comment by techman55** [comment]
I got it! Idk what I did wrong before but it works now. I think I ran the executable outside of the source files...

Thanks for all the help!

**Comment by master7720** [comment]
heres a bugfix dont use a mac

**Comment by agnlt64** [comment]
I followed all the steps above, and I get another linking error:
```
==== Building bin2c (debug) ====
Creating ../../osx-arm64/obj/Debug/bin2c
Creating ../../osx-arm64/obj/Debug/bin2c/tools/bin2c
bin2c.cpp
Linking bin2c
Undefined symbols for architecture arm64:
  "operator delete(void*)", referenced from:
      Bin2cWriter::~Bin2cWriter() in bin2c.o
      bx::MemoryBlock::~MemoryBlock() in bin2c.o
      bx::MemoryWriter::~MemoryWriter() in bin2c.o
      bx::FileReader::~FileReader() in libbxDebug.a(file.o)
      bx::FileWriter::~FileWriter() in libbxDebug.a(file.o)
      bx::DirectoryReader::~DirectoryReader() in libbxDebug.a(file.o)
      bx::FileReaderImpl::~FileReaderImpl() in libbxDebug.a(file.o)
      ...
  "___cxa_guard_acquire", referenced from:
      bx::getStdIn() in libbxDebug.a(file.o)
      bx::getStdOut() in libbxDebug.a(file.o)
      bx::getStdErr() in libbxDebug.a(file.o)
      bx::getNullOut() in libbxDebug.a(file.o)
      bx::getDebugOut() in libbxDebug.a(debug.o)
      bx::getTempPath(char*, unsigned int*) in libbxDebug.a(filepath.o)
  "___cxa_guard_release", referenced from:
      bx::getStdIn() in libbxDebug.a(file.o)
      bx::getStdOut() in libbxDebug.a(file.o)
      bx::getStdErr() in libbxDebug.a(file.o)
      bx::getNullOut() in libbxDebug.a(file.o)
      bx::getDebugOut() in libbxDebug.a(debug.o)
      bx::getTempPath(char*, unsigned int*) in libbxDebug.a(filepath.o)
  "___cxa_pure_virtual", referenced from:
      vtable for bx::WriterI in bin2c.o
      vtable for bx::MemoryBlockI in bin2c.o
      vtable for bx::WriterSeekerI in bin2c.o
      vtable for bx::SeekerI in bin2c.o
      vtable for bx::FileReaderI in libbxDebug.a(file.o)
      vtable for bx::ReaderSeekerI in libbxDebug.a(file.o)
      vtable for bx::SeekerI in libbxDebug.a(file.o)
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [../../osx-arm64/bin/bin2cDebug] Error 1
make[2]: *** [bin2c] Error 2
make[1]: *** [osx-arm64-debug] Error 2
make: *** [libs] Error 2
```
Since I changed all the appropiate files, idk what I have done wrong :(
My config is:
```
clang++ -v:
  Using built-in specs.
  COLLECT_GCC=g++-12
  COLLECT_LTO_WRAPPER=/opt/homebrew/Cellar/gcc/12.2.0/bin/../libexec/gcc/aarch64-apple-darwin22/12/lto-wrapper
  Target: aarch64-apple-darwin22
  Configured with: ../configure --prefix=/opt/homebrew/opt/gcc --libdir=/opt/homebrew/opt/gcc/lib/gcc/current --disable-nls --enable-checking=release --with-gcc-major-version-only --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-12 --with-gmp=/opt/homebrew/opt/gmp --with-mpfr=/opt/homebrew/opt/mpfr --with-mpc=/opt/homebrew/opt/libmpc --with-isl=/opt/homebrew/opt/isl --with-zstd=/opt/homebrew/opt/zstd --with-pkgversion='Homebrew GCC 12.2.0' --with-bugurl=https://github.com/Homebrew/homebrew-core/issues --with-system-zlib --build=aarch64-apple-darwin22 --with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk
  Thread model: posix
  Supported LTO compression algorithms: zlib zstd
  gcc version 12.2.0 (Homebrew GCC 12.2.0)
xcodebuild -version:
  Xcode 14.2
  Build version 14C18
```
I'm using macOS Ventura 13.1.

**Comment by Adamkob12** [comment]
> Make sure to clean your build files (`rm -rf lib/bx/.build`), or use `make clean` inside the `bx` project folder.

mkdir -p ./bin
export LD_PATH="-framework QuartzCore -framework Cocoa -framework Carbon -framework Metal -framework CoreFoundation -framework IOKit"
cd lib/bx && make osx-arm64
make[1]: *** No rule to make target `osx-arm64'.  Stop.
make: *** [libs] Error 2

Did everything, what am I missing?  ^ error

EDIT: Solved! I rm -rf'ed the project and recloned it. follow both steps: 1) https://github.com/jdah/minecraft-again/issues/2#issuecomment-1014977947 2) https://github.com/jdah/minecraft-again/issues/2#issuecomment-1014996349 
and that should be good
